[phases.setup]
nixPkgs = [
    "python3", 
    "gcc", 
    "pkg-config", 
    "cmake",
    "cairo", 
    "pango", 
    "freetype", 
    "libjpeg", 
    "zlib", 
    "ninja", 
    "meson"
]

[phases.install]
# Definimos as variáveis de ambiente diretamente na fase de instalação
# para que o pip e o meson encontrem os pacotes do Nix
cmds = [
    "python -m venv /opt/venv",
    "/opt/venv/bin/pip install --upgrade pip",
    "export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/lib/pkgconfig:/usr/share/pkgconfig:/root/.nix-profile/lib/pkgconfig",
    "/opt/venv/bin/pip install -r requirements.txt"
]

[start]
cmd = "/opt/venv/bin/python manage.py migrate && /opt/venv/bin/gunicorn app.wsgi:application --bind 0.0.0.0:$PORT"
