[phases.setup]
# Usamos .dev para garantir que os headers de compilação estejam presentes
nixPkgs = [
    "python3", 
    "gcc", 
    "pkg-config", 
    "cairo.dev", 
    "pango.dev", 
    "freetype.dev", 
    "libjpeg.dev", 
    "zlib.dev", 
    "ninja", 
    "meson"
]

[variables]
# Ajuda o pkg-config a localizar as bibliotecas no ambiente Nix
PKG_CONFIG_PATH = "/root/.nix-profile/lib/pkgconfig"

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    "/opt/venv/bin/pip install --upgrade pip",
    "/opt/venv/bin/pip install -r requirements.txt"
]

[start]
cmd = "/opt/venv/bin/python manage.py migrate && /opt/venv/bin/gunicorn app.wsgi:application --bind 0.0.0.0:$PORT"
