[phases.setup]
# Adicionamos pacotes que fornecem os headers necess√°rios para o ReportLab 3.6
nixPkgs = [
    "python3", 
    "gcc", 
    "binutils",
    "gnumake",
    "libjpeg", 
    "zlib", 
    "freetype"
]

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    "/opt/venv/bin/pip install --upgrade pip setuptools wheel",
    "/opt/venv/bin/pip install -r requirements.txt"
]

[start]
cmd = "/opt/venv/bin/python manage.py collectstatic --noinput && /opt/venv/bin/python manage.py migrate && /opt/venv/bin/gunicorn app.wsgi:application --bind 0.0.0.0:$PORT"
